mapping_rules:
  nodes:
    application:
      type: "application-component"
      attributes:
        - label
        - description
    business:
      type: "business-actor"
      attributes:
        - label
        - description
    technology:
      type: "technology-node"
      attributes:
        - label
        - description
    # Terraform specific mappings
    aws_instance:
      type: "technology-device"
      attributes:
        - label
        - shape
    aws_vpc:
      type: "technology-network"
      attributes:
        - label
        - shape
    aws_subnet:
      type: "technology-network"
      attributes:
        - label
        - shape
    aws_security_group:
      type: "technology-network"
      attributes:
        - label
        - shape
    provider:
      type: "technology-service"
      attributes:
        - label
        - shape
    var:
      type: "business-object"
      attributes:
        - label
        - shape

  relationships:
    uses:
      type: "serving-relationship"
      attributes:
        - label
    flows:
      type: "flow-relationship"
      attributes:
        - label
    # Terraform specific relationships
    depends:
      type: "serving-relationship"
      attributes:
        - label
    creates:
      type: "assignment-relationship"
      attributes:
        - label
    triggers:
      type: "triggering-relationship"
      attributes:
        - label

archimate:
  namespace: "http://www.opengroup.org/xsd/archimate/3.0/"
  schema_location: "http://www.opengroup.org/xsd/archimate/3.0/ http://www.opengroup.org/xsd/archimate/3.0/archimate3_Diagram.xsd" 