impressum:
  company_name: Aymon Fournier
  copyright_year: '2025'
  country: Your Country
  email: info@aymon.dev
  phone: Your Phone Number
  street: Your Street Address
  zip_city: Your ZIP and City
privacy:
  company_name: Aymon Fournier
  copyright_year: '2025'
  country: Your Country
  email: info@aymon.dev
  hoster: Your Hosting Provider
  phone: Your Phone Number
  street: Your Street Address
  zip_city: Your ZIP and City
